

------------ INSERTS INTO CUSTOMER DETAILS-----------


INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CREATED_AT,MODIFIED_AT,TITLE,FIRST_NAME,LAST_NAME,GENDER)
 VALUES(SEQ_CUSTOMER_ID.nextval,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mr.','Mohammad','Uzair','MALE');

INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CREATED_AT,MODIFIED_AT,TITLE,FIRST_NAME,LAST_NAME,GENDER)
 VALUES(SEQ_CUSTOMER_ID.nextval,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mr.','Mohammad','Salah','MALE');