

------------ INSERTS INTO CUSTOMER DETAILS-----------


INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CREATED_AT,MODIFIED_AT,TITLE,FIRST_NAME,LAST_NAME,GENDER)
 VALUES(100,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mr.','Mohammad','Uzair','MALE');

INSERT INTO CUSTOMER_DETAILS(CUSTOMER_ID,CREATED_AT,MODIFIED_AT,TITLE,FIRST_NAME,LAST_NAME,GENDER)
 VALUES(101,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Mr.','Mohammad','Salah','MALE');


------------ INSERTS INTO ACCOUNT DETAILS-----------


INSERT INTO ACCOUNT_DETAILS(ACCOUNT_NUMBER,CREATED_AT,MODIFIED_AT,ACCOUNT_CURRENCY,CURRENT_BALANCE,CUSTOMER_ID)
 VALUES(1000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'AED',1000,100);


INSERT INTO ACCOUNT_DETAILS(ACCOUNT_NUMBER,CREATED_AT,MODIFIED_AT,ACCOUNT_CURRENCY,CURRENT_BALANCE,CUSTOMER_ID)
 VALUES(1001,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'AED',1000,101);

