

DROP TABLE IF EXISTS ACCOUNT_DETAILS;

CREATE TABLE ACCOUNT_DETAILS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250),
  ACCOUNT_CURRENCY VARCHAR(250) NOT NULL,
  CURRENT_BALANCE INT
);